#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

# Load or attach tmux session at startup
# [shell]
# args = ["-l", "-c", "tmux attach || tmux"]
# program = "/bin/zsh"

[font]
size = 15

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

# Thanks to PaperColor
[colors.primary]
background = '#eeeeee'
foreground = '#444444'

[colors.cursor]
text = '#eeeeee'
cursor = '#444444'

[colors.normal]
black   = '#eeeeee'
red     = '#af0000'
green   = '#008700'
yellow  = '#d75f00'
blue    = '#005f87'
magenta = '#8700af'
cyan    = '#0087af'
white   = '#444444'

[colors.bright]
black   = '#eeeeee'
red     = '#af0000'
green   = '#008700'
yellow  = '#ffaf00'
blue    = '#00afaf'
magenta = '#af87d7'
cyan    = '#5fafd7'
white   = '#585858'
