#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

# Load or attach tmux session at startup
[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

[window.position]
x = 0
y = 0

# Thanks to Jellybeans color scheme
[colors.primary]
background = '0x121212'
foreground = '0xdedede'

[colors.cursor]
text = '0xffffff'
cursor = '0xffa460'

[colors.normal]
black   = '0x929292'
red     = '0xe27373'
green   = '0x94b979'
yellow  = '0xffba7b'
blue    = '0x97bedc'
magenta = '0xe1c0fa'
cyan    = '0x00988e'
white   = '0xdedede'

[colors.bright]
black   = '0xbdbdbd'
red     = '0xffa1a1'
green   = '0xbddeab'
yellow  = '0xffdca0'
blue    = '0xb1d8f6'
magenta = '0xfbdaff'
cyan    = '0x1ab2a8'
white   = '0xffffff'
