[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 13

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Command"

[scrolling]
history = 20000
multiplier = 2

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "full"
dynamic_padding = false
opacity = 1

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 2

[window.position]
x = 0
y = 0
