#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

# Load or attach tmux session at startup
[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 14

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
blur = true
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

[window.position]
x = 0
y = 0

# Thanks to Jellybeans
[colors.primary]
background = "#161616"
foreground = "#e4e4e4"

[colors.cursor]
text = "#feffff"
cursor = "#ffb472"

[colors.normal]
black = "#a3a3a3"
red = "#e98885"
green = "#a3c38b"
yellow = "#ffc68d"
blue = "#a6cae2"
magenta = "#e7cdfb"
cyan = "#00a69f"
white = "#e4e4e4"

[colors.bright]
black = "#c8c8c8"
red = "#ffb2b0"
green = "#c8e2b9"
yellow = "#ffe1af"
blue = "#bddff7"
magenta = "#fce2ff"
cyan = "#0bbdb6"
white = "#feffff"

[colors.selection]
text = "#5963a2"
background = "#f6f6f6"
