#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

# Load or attach tmux session at startup
[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 14

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

[window.position]
x = 0
y = 0

# Thanks to https://github.com/NLKNguyen/papercolor-theme
[colors.primary]
background = '#eeeeee'
foreground = '#444444'

[colors.cursor]
text = '#eeeeee'
cursor = '#444444'

[colors.normal]
black   = '#eeeeee'
red     = '#af0000'
green   = '#008700'
yellow  = '#5f8700'
blue    = '#0087af'
magenta = '#878787'
cyan    = '#005f87'
white   = '#444444'

[colors.bright]
black   = '#bcbcbc'
red     = '#d70000'
green   = '#d70087'
yellow  = '#8700af'
blue    = '#d75f00'
magenta = '#d75f00'
cyan    = '#005faf'
white   = '#005f87'
