#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

# Load or attach tmux session at startup
[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

[window.position]
x = 0
y = 0

# Thanks to Catppuccin
[colors.primary]
background = '#eff1f5'
foreground = '#4c4f69'

[colors.cursor]
text = '#eff1f5'
cursor = '#dc8a78'

[colors.vi_mode_cursor]
text = '#eff1f5'
cursor = '#7287fd'

[colors.search.matches]
foreground = '#eff1f5'
background = '#6c6f85'

[colors.search.focused_match]
foreground = '#eff1f5'
background = '#40a02b'

[colors.footer_bar]
foreground = '#eff1f5'
background = '#6c6f85'

[colors.hints.start]
foreground = '#eff1f5'
background = '#df8e1d'

[colors.hints.end]
foreground = '#eff1f5'
background = '#6c6f85'

[colors.selection]
text = '#eff1f5'
background = '#dc8a78'

[colors.normal]
black = '#5c5f77'
red = '#d20f39'
green = '#40a02b'
yellow = '#df8e1d'
blue = '#1e66f5'
magenta = '#ea76cb'
cyan = '#179299'
white = '#acb0be'

[colors.bright]
black = '#6c6f85'
red = '#d20f39'
green = '#40a02b'
yellow = '#df8e1d'
blue = '#1e66f5'
magenta = '#ea76cb'
cyan = '#179299'
white = '#bcc0cc'

[colors.dim]
black = '#5c5f77'
red = '#d20f39'
green = '#40a02b'
yellow = '#df8e1d'
blue = '#1e66f5'
magenta = '#ea76cb'
cyan = '#179299'
white = '#acb0be'
