[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 14

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "full"
dynamic_padding = false
opacity = 1

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 2

[window.position]
x = 0
y = 0

[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'
