theme = "tokyodark"

[editor]
mouse = true
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

[keys.normal.space]
o = "file_picker_in_current_buffer_directory"
G = ":pipe-to zellij run -c -i -- lazygit"
T = ":pipe-to zellij action new-pane -d down"
